### ISSUE TITLE
URL encoding with Slackbot

### ISSUE THREAD

**Issue by thebuilder** [replit/evalbot#2]
Special chars are lost when using the slackbot.

The following examples will fail when:

``` js
console.log('test');
```

Is converted to: 
console.log(‘test’);

``` js
function fib(n) {
  if (n < 2) {
    return n;
  } else {
    return fib(n - 1) + fib(n - 2);
  }
}
console.log("Fib(9) = " + fib(9));
```

The < is escaped: http://goo.gl/KK6T5x

**Comment by masad-frost** [comment]
Fixed in 044ce16c, thanks
